name: Run the test suite

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
        allow-prereleases: true
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install the project with its test dependencies
      run: pip install -e .[test]
    - name: Test with pytest
      run: pytest -v
